# Server
server:
  port: ${PORT:7777}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: 'INFO'
    com.microservices.scn.comic: 'DEBUG'

management:
  security:
    enabled: false

# Discovery Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/