# HTTP
server:
  port: ${EUREKA_PORT:1111}

management:
  security:
    enabled: false

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.microservices.scn: 'DEBUG'

# Configuration
eureka:
  instance:
    hostname: localhost
    #prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false